//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebForms.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblEmployee", Namespace="http://schemas.datacontract.org/2004/07/ProjectWCFLayer")]
    [System.SerializableAttribute()]
    public partial class tblEmployee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int empnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string enameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> mgrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int empno {
            get {
                return this.empnoField;
            }
            set {
                if ((this.empnoField.Equals(value) != true)) {
                    this.empnoField = value;
                    this.RaisePropertyChanged("empno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ename {
            get {
                return this.enameField;
            }
            set {
                if ((object.ReferenceEquals(this.enameField, value) != true)) {
                    this.enameField = value;
                    this.RaisePropertyChanged("ename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> mgr {
            get {
                return this.mgrField;
            }
            set {
                if ((this.mgrField.Equals(value) != true)) {
                    this.mgrField = value;
                    this.RaisePropertyChanged("mgr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblCustomer", Namespace="http://schemas.datacontract.org/2004/07/ProjectWCFLayer")]
    [System.SerializableAttribute()]
    public partial class tblCustomer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EmployeeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustorName {
            get {
                return this.CustorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustorNameField, value) != true)) {
                    this.CustorNameField = value;
                    this.RaisePropertyChanged("CustorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblSale", Namespace="http://schemas.datacontract.org/2004/07/ProjectWCFLayer")]
    [System.SerializableAttribute()]
    public partial class tblSale : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmployee", ReplyAction="http://tempuri.org/IService1/GetEmployeeResponse")]
        ProjectWebForms.ServiceReference1.tblEmployee[] GetEmployee();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmployee", ReplyAction="http://tempuri.org/IService1/GetEmployeeResponse")]
        System.Threading.Tasks.Task<ProjectWebForms.ServiceReference1.tblEmployee[]> GetEmployeeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomer", ReplyAction="http://tempuri.org/IService1/GetCustomerResponse")]
        ProjectWebForms.ServiceReference1.tblCustomer[] GetCustomer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomer", ReplyAction="http://tempuri.org/IService1/GetCustomerResponse")]
        System.Threading.Tasks.Task<ProjectWebForms.ServiceReference1.tblCustomer[]> GetCustomerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSales", ReplyAction="http://tempuri.org/IService1/GetSalesResponse")]
        ProjectWebForms.ServiceReference1.tblSale[] GetSales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSales", ReplyAction="http://tempuri.org/IService1/GetSalesResponse")]
        System.Threading.Tasks.Task<ProjectWebForms.ServiceReference1.tblSale[]> GetSalesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddEmployee", ReplyAction="http://tempuri.org/IService1/AddEmployeeResponse")]
        ProjectWebForms.ServiceReference1.tblEmployee AddEmployee(int empno, string ename, int mgr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddEmployee", ReplyAction="http://tempuri.org/IService1/AddEmployeeResponse")]
        System.Threading.Tasks.Task<ProjectWebForms.ServiceReference1.tblEmployee> AddEmployeeAsync(int empno, string ename, int mgr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteEmployee", ReplyAction="http://tempuri.org/IService1/DeleteEmployeeResponse")]
        ProjectWebForms.ServiceReference1.tblEmployee DeleteEmployee(int empno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteEmployee", ReplyAction="http://tempuri.org/IService1/DeleteEmployeeResponse")]
        System.Threading.Tasks.Task<ProjectWebForms.ServiceReference1.tblEmployee> DeleteEmployeeAsync(int empno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditEmployee", ReplyAction="http://tempuri.org/IService1/EditEmployeeResponse")]
        ProjectWebForms.ServiceReference1.tblEmployee EditEmployee(int empno, string ename, int mgr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditEmployee", ReplyAction="http://tempuri.org/IService1/EditEmployeeResponse")]
        System.Threading.Tasks.Task<ProjectWebForms.ServiceReference1.tblEmployee> EditEmployeeAsync(int empno, string ename, int mgr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCustomer", ReplyAction="http://tempuri.org/IService1/AddCustomerResponse")]
        ProjectWebForms.ServiceReference1.tblCustomer AddCustomer(int customerid, string custorname, string address, int employeeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCustomer", ReplyAction="http://tempuri.org/IService1/AddCustomerResponse")]
        System.Threading.Tasks.Task<ProjectWebForms.ServiceReference1.tblCustomer> AddCustomerAsync(int customerid, string custorname, string address, int employeeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCustomer", ReplyAction="http://tempuri.org/IService1/DeleteCustomerResponse")]
        ProjectWebForms.ServiceReference1.tblCustomer DeleteCustomer(int customerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCustomer", ReplyAction="http://tempuri.org/IService1/DeleteCustomerResponse")]
        System.Threading.Tasks.Task<ProjectWebForms.ServiceReference1.tblCustomer> DeleteCustomerAsync(int customerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditCustomer", ReplyAction="http://tempuri.org/IService1/EditCustomerResponse")]
        ProjectWebForms.ServiceReference1.tblCustomer EditCustomer(int customerid, string custorname, string address, int employeeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditCustomer", ReplyAction="http://tempuri.org/IService1/EditCustomerResponse")]
        System.Threading.Tasks.Task<ProjectWebForms.ServiceReference1.tblCustomer> EditCustomerAsync(int customerid, string custorname, string address, int employeeid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ProjectWebForms.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ProjectWebForms.ServiceReference1.IService1>, ProjectWebForms.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProjectWebForms.ServiceReference1.tblEmployee[] GetEmployee() {
            return base.Channel.GetEmployee();
        }
        
        public System.Threading.Tasks.Task<ProjectWebForms.ServiceReference1.tblEmployee[]> GetEmployeeAsync() {
            return base.Channel.GetEmployeeAsync();
        }
        
        public ProjectWebForms.ServiceReference1.tblCustomer[] GetCustomer() {
            return base.Channel.GetCustomer();
        }
        
        public System.Threading.Tasks.Task<ProjectWebForms.ServiceReference1.tblCustomer[]> GetCustomerAsync() {
            return base.Channel.GetCustomerAsync();
        }
        
        public ProjectWebForms.ServiceReference1.tblSale[] GetSales() {
            return base.Channel.GetSales();
        }
        
        public System.Threading.Tasks.Task<ProjectWebForms.ServiceReference1.tblSale[]> GetSalesAsync() {
            return base.Channel.GetSalesAsync();
        }
        
        public ProjectWebForms.ServiceReference1.tblEmployee AddEmployee(int empno, string ename, int mgr) {
            return base.Channel.AddEmployee(empno, ename, mgr);
        }
        
        public System.Threading.Tasks.Task<ProjectWebForms.ServiceReference1.tblEmployee> AddEmployeeAsync(int empno, string ename, int mgr) {
            return base.Channel.AddEmployeeAsync(empno, ename, mgr);
        }
        
        public ProjectWebForms.ServiceReference1.tblEmployee DeleteEmployee(int empno) {
            return base.Channel.DeleteEmployee(empno);
        }
        
        public System.Threading.Tasks.Task<ProjectWebForms.ServiceReference1.tblEmployee> DeleteEmployeeAsync(int empno) {
            return base.Channel.DeleteEmployeeAsync(empno);
        }
        
        public ProjectWebForms.ServiceReference1.tblEmployee EditEmployee(int empno, string ename, int mgr) {
            return base.Channel.EditEmployee(empno, ename, mgr);
        }
        
        public System.Threading.Tasks.Task<ProjectWebForms.ServiceReference1.tblEmployee> EditEmployeeAsync(int empno, string ename, int mgr) {
            return base.Channel.EditEmployeeAsync(empno, ename, mgr);
        }
        
        public ProjectWebForms.ServiceReference1.tblCustomer AddCustomer(int customerid, string custorname, string address, int employeeid) {
            return base.Channel.AddCustomer(customerid, custorname, address, employeeid);
        }
        
        public System.Threading.Tasks.Task<ProjectWebForms.ServiceReference1.tblCustomer> AddCustomerAsync(int customerid, string custorname, string address, int employeeid) {
            return base.Channel.AddCustomerAsync(customerid, custorname, address, employeeid);
        }
        
        public ProjectWebForms.ServiceReference1.tblCustomer DeleteCustomer(int customerid) {
            return base.Channel.DeleteCustomer(customerid);
        }
        
        public System.Threading.Tasks.Task<ProjectWebForms.ServiceReference1.tblCustomer> DeleteCustomerAsync(int customerid) {
            return base.Channel.DeleteCustomerAsync(customerid);
        }
        
        public ProjectWebForms.ServiceReference1.tblCustomer EditCustomer(int customerid, string custorname, string address, int employeeid) {
            return base.Channel.EditCustomer(customerid, custorname, address, employeeid);
        }
        
        public System.Threading.Tasks.Task<ProjectWebForms.ServiceReference1.tblCustomer> EditCustomerAsync(int customerid, string custorname, string address, int employeeid) {
            return base.Channel.EditCustomerAsync(customerid, custorname, address, employeeid);
        }
    }
}
